### ISSUE TITLE
Not able to run the codebase

### ISSUE THREAD

**Issue by sandeep99063** [kaltura/kaltura-ng#138]
After cloning the repository when i try to run it using either 'ng serve' or 'ng serve projectName' i face following  issue:- 
![issue](https://user-images.githubusercontent.com/12955095/46910793-ae24dd00-cf68-11e8-9cdb-e7ba11e36e00.png)
my system has all dependency as mentioned in "package.json" that are required to run the projects.
i.e. 
1. angular cli :- ^6.1.9
2. typescript:- 2.9.2
3.  Node:- 8.11.3
please look into the following issue and provide the necessary solution.

**Comment by kaltura-hooks** [comment]
Hi @sandeep99063,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by esakal** [comment]
Hi @sandeep99063, thanks for reaching out.
What are you trying to achieve? Are you trying to run the kmc-ng project? because there is no point serving the kaltura-ng which is infrastructure projects for kmc-ng. If you do try to build the kmc-ng use the [following guide](https://github.com/kaltura/kmc-ng#run-the-application). Otherwise please provide more information about your end goal.

Eran.

**Comment by sandeep99063** [comment]
Hi @esakal, thanks for the quick response.
I am trying to integrate Kaltura Video Platform and I am looking for some angular6 repository which can help me in creating my own kaltura video upload widget same as the one provided here in jquery (i.e https://blueimp.github.io/jQuery-File-Upload/). So i am exploring the kaltura-ng repository with a goal to find some help in creating a video upload widget.
Please suggest some help.

Thank you in advance,

**Comment by jessp01** [comment]
Hi @sandeep99063,

Please have a look at https://github.com/kaltura/kaltura-parallel-upload-resumablejs.
